name: giphy_get
description: Pick EMOJI,STICKER or GIF from Giphy in pure dart code. Support Android,iOS,Web and Desktop.
version: 3.2.0
homepage: https://github.com/bazospa/giphy_get

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: 
  extended_image: ^7.0.0
  flutter_staggered_grid_view: 
  meta: 
  http: 
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.7
  pedantic: ^1.11.0
  matcher: ^0.12.10

flutter:
  assets:
    - assets/img/
